config/routes.rb
Rails.application.routes.draw do
  resources :cryptocurrencies
  devise_for :users
  root 'home#index'
  
  get 'home/about'
  get 'home/lookup'

  post'/home/lookup' => 'home/lookup'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cryptocurrency.rb
class Cryptocurrency < ApplicationRecord
    belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         has_many :cryptocurrencies
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/cryptocurrencies_controller.rb
class CryptocurrenciesController < ApplicationController
  before_action :set_cryptocurrency, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  before_action :correct_user, only: [:show, :edit, :update, :destroy]

  # GET /cryptocurrencies
  # GET /cryptocurrencies.json
  def index
    @cryptocurrencies = Cryptocurrency.all

    require 'net/http'
    require 'json'

    @url = 'https://api.coinmarketcap.com/v1/ticker/'
    @uri = URI(@url)
    @response = Net::HTTP.get(@uri)
    @lookup_crypto = JSON.parse(@response)

    @profit_loss = 0
  end

  # GET /cryptocurrencies/1
  # GET /cryptocurrencies/1.json
  def show
    require 'net/http'
    require 'json'

    @url = 'https://api.coinmarketcap.com/v1/ticker/'
    @uri = URI(@url)
    @response = Net::HTTP.get(@uri)
    @show_crypto = JSON.parse(@response)
  end

  # GET /cryptocurrencies/new
  def new
    @cryptocurrency = Cryptocurrency.new
  end

  # GET /cryptocurrencies/1/edit
  def edit
  end

  # POST /cryptocurrencies
  # POST /cryptocurrencies.json
  def create
    @cryptocurrency = Cryptocurrency.new(cryptocurrency_params)

    respond_to do |format|
      if @cryptocurrency.save
        format.html { redirect_to @cryptocurrency, notice: 'Cryptocurrency was successfully created.' }
        format.json { render :show, status: :created, location: @cryptocurrency }
      else
        format.html { render :new }
        format.json { render json: @cryptocurrency.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cryptocurrencies/1
  # PATCH/PUT /cryptocurrencies/1.json
  def update
    respond_to do |format|
      if @cryptocurrency.update(cryptocurrency_params)
        format.html { redirect_to @cryptocurrency, notice: 'Cryptocurrency was successfully updated.' }
        format.json { render :show, status: :ok, location: @cryptocurrency }
      else
        format.html { render :edit }
        format.json { render json: @cryptocurrency.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cryptocurrencies/1
  # DELETE /cryptocurrencies/1.json
  def destroy
    @cryptocurrency.destroy
    respond_to do |format|
      format.html { redirect_to cryptocurrencies_url, notice: 'Cryptocurrency was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cryptocurrency
      @cryptocurrency = Cryptocurrency.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cryptocurrency_params
      params.require(:cryptocurrency).permit(:symbol, :user_id, :cost_per, :amount_owned)
    end
    
    def correct_user
      @correct = current_user.cryptocurrencies.find_by(id: params[:id])
      redirect_to cryptocurrencies_path, notice: "Not Authorised to edit this entry" if @correct.nil?
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    require 'net/http'
    require 'json'

    @url = 'https://api.coinmarketcap.com/v1/ticker/'
    @uri = URI(@url)
    @response = Net::HTTP.get(@uri)
    @coins = JSON.parse(@response)

    @my_coins = ["BTC", "XRP", "ADA", "XLM", "STEEM"]
  end

  def about
  end

  def lookup
    require 'net/http'
    require 'json'

    @url = 'https://api.coinmarketcap.com/v1/ticker/'
    @uri = URI(@url)
    @response = Net::HTTP.get(@uri)
    @lookup_coin = JSON.parse(@response)

    @symbol = params[:sym]

    if @symbol
      @symbol = @symbol.upcase
    end

    if @symbol == ""
      @symbol = 'Hey you forgot to enter a currency!'
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cryptocurrencies_helper.rb
module CryptocurrenciesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/cryptocurrencies/_form.html.erb
<%= form_with(model: cryptocurrency, local: true) do |form| %>
  <% if cryptocurrency.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(cryptocurrency.errors.count, "error") %> prohibited this cryptocurrency from being saved:</h2>

      <ul>
      <% cryptocurrency.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :symbol %>
    <%= form.text_field :symbol, id: :cryptocurrency_symbol %>
  </div>

  <div class="field">
    <%= form.number_field :user_id, id: :cryptocurrency_user_id, value: current_user.id, type: "hidden" %>
  </div>

  <div class="field">
    <%= form.label :cost_per %>
    <%= form.text_field :cost_per, id: :cryptocurrency_cost_per %>
  </div>

  <div class="field">
    <%= form.label :amount_owned %>
    <%= form.text_field :amount_owned, id: :cryptocurrency_amount_owned %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/cryptocurrencies/edit.html.erb
<h1>Editing Cryptocurrency</h1>

<%= render 'form', cryptocurrency: @cryptocurrency %>

<%= link_to 'Show', @cryptocurrency %> |
<%= link_to 'Back', cryptocurrencies_path %>

app/views/cryptocurrencies/index.html.erb
<h1>Cryptocurrencies</h1>

<table class="table table-striped table-bordered table-hover">
  <br>
  <thead>
    <tr>
      <th>Name</th>
      <th>Current Price</th>
      <th>Rank</th>
      <th>1 Hour</th>
      <th>24 Hours</th>
      <th>7 Days</th>
      <th>Current Value</th>
      <th>Total Paid</th>
      <th>Profit/Loss</th>
      <th>Cost Paid per</th>
      <th>Amount owned</th>
    </tr>
  </thead>

  <tbody>
    <% @cryptocurrencies.each do |cryptocurrency| %>
      <% if cryptocurrency.user_id == current_user.id %>
        <% if cryptocurrency.symbol %>
          <% cryptocurrency.symbol = cryptocurrency.symbol.upcase %>
        <% end %>
        <tr>
        <% for x in @lookup_crypto %>
            <% if cryptocurrency.symbol == x["symbol"] %>
                <td><%= link_to x["name"], cryptocurrency %></td>
                <td>$<%= x["price_usd"] %></td>
                <td><%= x["rank"] %></td>
                <td><%= x["percent_change_1h"] %>%</td>
                <td><%= x["percent_change_24h"] %>%</td>
                <td><%= x["percent_change_7d"] %>%</td>
                <td>$<%= x["price_usd"].to_d * cryptocurrency.amount_owned %></td>
                <td>$<%= cryptocurrency.cost_per * cryptocurrency.amount_owned %></td>
                <td>$<%= (x["price_usd"].to_d * cryptocurrency.amount_owned) - (cryptocurrency.cost_per * cryptocurrency.amount_owned) %></td>
                <% @profit_loss += (x["price_usd"].to_d * cryptocurrency.amount_owned) - (cryptocurrency.cost_per * cryptocurrency.amount_owned) %>
            <% end %>
      <% end %>
        
          <td>$<%= cryptocurrency.cost_per %></td>
          <td><%= cryptocurrency.amount_owned %></td>
        </tr>
        <% end %>
    <% end %>
  </tbody>
</table>

<br>

<strong>Portfolio Profit/Loss:</strong> <%= number_to_currency(@profit_loss) %>

<br>

<%= link_to 'New Cryptocurrency', new_cryptocurrency_path, class: "btn btn-primary" %>

app/views/cryptocurrencies/new.html.erb
<h1>New Cryptocurrency</h1>

<%= render 'form', cryptocurrency: @cryptocurrency %>

<%= link_to 'Back', cryptocurrencies_path %>

app/views/cryptocurrencies/show.html.erb
<% for x in @show_crypto %>
    <% if @cryptocurrency.symbol.upcase == x["symbol"] %>
        <% crypto_name = x["name"] %>
        <% crypto_price = x["price_usd"] %>
        <br>
        <% crypto_rank = x["rank"] %>
        <br>
    <% end %>
<% end %>

<div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title"><%= crypto_name %></h3>
  </div>

  <div class="panel-body">
    <p>
      <h1><%= @cryptocurrency.symbol.upcase %></h1>
    </p>

    <p>
      <strong>Current Price:</strong> <%= crypto_price %>
    </p>

    <p>
      <strong>Rank:</strong> <%= crypto_rank %>
    </p>

    <p>
      <strong>Cost per:</strong>
      <%= @cryptocurrency.cost_per %>
    </p>

    <p>
      <strong>Amount owned:</strong>
      <%= @cryptocurrency.amount_owned %>
    </p>
  </div>

  <div class="panel-footer">
    <%= link_to 'Edit', edit_cryptocurrency_path(@cryptocurrency) %> |
    <%= link_to 'Delete', cryptocurrency_path(@cryptocurrency), method: :delete, data: { confirm: 'Are you sure?' } %> |
    <%= link_to 'Back', cryptocurrencies_path %>
  </div>
</div>

app/views/home/_flash.html.erb
<% flash.each do |name, msg| %>
    <div class="alert alert-warning alert-dismissible">
        <button class="close" data-dismiss="alert">
            <i class="glyphicon glyphicon-remove-circle"></i>
        </button>
        <%= content_tag(:div, msg) %>
    </div>
<% end %>

app/views/home/_navbar.html.erb
<nav class="navbar navbar-default">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1"
                aria-expanded="false">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <%= link_to 'Crypto Portfolio', root_path, class: "navbar-brand" %>
        </div>

        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav navbar-right">
                <li><%= link_to 'Home', root_path %></li>
                <li><%= link_to 'About Us', home_about_path %></li>
                <li><%= link_to 'Lookup', home_lookup_path %></li>

                <% if user_signed_in? %>
                    <li><%= link_to 'List Cryptos', cryptocurrencies_path %></li>
                    <li><%= link_to 'Add New', new_cryptocurrency_path %></li>
                    <li><%= link_to 'Edit Profile', edit_user_registration_path %></li>  
                    <li><%= link_to 'Log Out', destroy_user_session_path, method: :delete %></li> 
                <% else %>
                    <li><%= link_to 'Sign Up', new_user_registration_path %></li>
                    <li><%= link_to 'Log In', new_user_session_path %></li> 
                <% end %>            
            </ul>
        </div>
    </div>
</nav>

app/views/home/about.html.erb
<h1>About Us</h1>
<p>My name is Sonya...</p>

app/views/home/index.html.erb
<h1>Homepage</h1>

<br>
<br>


<% @coins %>

<% for x in @coins %>
    <% for coin in @my_coins %>
        <% if coin == x["symbol"] %>
            <%= x["name"] %>: $<%= x["price_usd"] %>
            <br>
            Rank: <%= x["rank"] %>
            <br>
        <% end %>
    <% end %>
<% end %>

app/views/home/lookup.html.erb
<h3>Crypto Currency Lookup</h3>
<br>

<%= form_tag home_lookup_path, :method => 'POST' do %>
    <%= text_field_tag 'sym', nil, placeholder: 'Enter Crypto Symbol', size: 50 %>
    <%= submit_tag 'Lookup Stock Quote' %>
<% end %>

<br> 

<% if @symbol %>
    <% for x in @lookup_coin %>
        <% if @symbol == x["symbol"] %>
            <%= x["name"] %>: $<%= x["price_usd"] %>
            <br>
            Rank: <%= x["rank"] %>
            <br>
        <% end %>
    <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
  <title>Crypto Currency Portfolio</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= csrf_meta_tags %>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
  <%= render 'home/navbar' %>

    <div class="container">
      <%= render 'home/flash' %>
      <%= yield %>
    </div>
    
</body>

</html>